// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3a00d74cca72a020, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type Service struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3a00d74cca72a020, []int{1}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Token struct {
	Issuer               *User                `protobuf:"bytes,1,opt,name=issuer" json:"issuer,omitempty"`
	Audience             *Service             `protobuf:"bytes,2,opt,name=audience" json:"audience,omitempty"`
	Expire               *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expire" json:"expire,omitempty"`
	Scopes               []string             `protobuf:"bytes,4,rep,name=scopes" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3a00d74cca72a020, []int{2}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetIssuer() *User {
	if m != nil {
		return m.Issuer
	}
	return nil
}

func (m *Token) GetAudience() *Service {
	if m != nil {
		return m.Audience
	}
	return nil
}

func (m *Token) GetExpire() *timestamp.Timestamp {
	if m != nil {
		return m.Expire
	}
	return nil
}

func (m *Token) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type ValidateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateUserRequest) Reset()         { *m = ValidateUserRequest{} }
func (m *ValidateUserRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateUserRequest) ProtoMessage()    {}
func (*ValidateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3a00d74cca72a020, []int{3}
}
func (m *ValidateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateUserRequest.Unmarshal(m, b)
}
func (m *ValidateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateUserRequest.Marshal(b, m, deterministic)
}
func (dst *ValidateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateUserRequest.Merge(dst, src)
}
func (m *ValidateUserRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateUserRequest.Size(m)
}
func (m *ValidateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateUserRequest proto.InternalMessageInfo

func (m *ValidateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ValidateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ValidateUserReply struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateUserReply) Reset()         { *m = ValidateUserReply{} }
func (m *ValidateUserReply) String() string { return proto.CompactTextString(m) }
func (*ValidateUserReply) ProtoMessage()    {}
func (*ValidateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3a00d74cca72a020, []int{4}
}
func (m *ValidateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateUserReply.Unmarshal(m, b)
}
func (m *ValidateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateUserReply.Marshal(b, m, deterministic)
}
func (dst *ValidateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateUserReply.Merge(dst, src)
}
func (m *ValidateUserReply) XXX_Size() int {
	return xxx_messageInfo_ValidateUserReply.Size(m)
}
func (m *ValidateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateUserReply proto.InternalMessageInfo

func (m *ValidateUserReply) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ValidateUserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserInfoRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3a00d74cca72a020, []int{5}
}
func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(dst, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetUserInfoReply struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReply) Reset()         { *m = GetUserInfoReply{} }
func (m *GetUserInfoReply) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReply) ProtoMessage()    {}
func (*GetUserInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3a00d74cca72a020, []int{6}
}
func (m *GetUserInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReply.Unmarshal(m, b)
}
func (m *GetUserInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReply.Marshal(b, m, deterministic)
}
func (dst *GetUserInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReply.Merge(dst, src)
}
func (m *GetUserInfoReply) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReply.Size(m)
}
func (m *GetUserInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReply proto.InternalMessageInfo

func (m *GetUserInfoReply) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *GetUserInfoReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetTokenInfoRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenInfoRequest) Reset()         { *m = GetTokenInfoRequest{} }
func (m *GetTokenInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenInfoRequest) ProtoMessage()    {}
func (*GetTokenInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3a00d74cca72a020, []int{7}
}
func (m *GetTokenInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenInfoRequest.Unmarshal(m, b)
}
func (m *GetTokenInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetTokenInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenInfoRequest.Merge(dst, src)
}
func (m *GetTokenInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenInfoRequest.Size(m)
}
func (m *GetTokenInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenInfoRequest proto.InternalMessageInfo

func (m *GetTokenInfoRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetTokenInfoReply struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
	Token                *Token   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenInfoReply) Reset()         { *m = GetTokenInfoReply{} }
func (m *GetTokenInfoReply) String() string { return proto.CompactTextString(m) }
func (*GetTokenInfoReply) ProtoMessage()    {}
func (*GetTokenInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3a00d74cca72a020, []int{8}
}
func (m *GetTokenInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenInfoReply.Unmarshal(m, b)
}
func (m *GetTokenInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenInfoReply.Marshal(b, m, deterministic)
}
func (dst *GetTokenInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenInfoReply.Merge(dst, src)
}
func (m *GetTokenInfoReply) XXX_Size() int {
	return xxx_messageInfo_GetTokenInfoReply.Size(m)
}
func (m *GetTokenInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenInfoReply proto.InternalMessageInfo

func (m *GetTokenInfoReply) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *GetTokenInfoReply) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "account.User")
	proto.RegisterType((*Service)(nil), "account.Service")
	proto.RegisterType((*Token)(nil), "account.Token")
	proto.RegisterType((*ValidateUserRequest)(nil), "account.ValidateUserRequest")
	proto.RegisterType((*ValidateUserReply)(nil), "account.ValidateUserReply")
	proto.RegisterType((*GetUserInfoRequest)(nil), "account.GetUserInfoRequest")
	proto.RegisterType((*GetUserInfoReply)(nil), "account.GetUserInfoReply")
	proto.RegisterType((*GetTokenInfoRequest)(nil), "account.GetTokenInfoRequest")
	proto.RegisterType((*GetTokenInfoReply)(nil), "account.GetTokenInfoReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Account service

type AccountClient interface {
	ValidateUserPassword(ctx context.Context, in *ValidateUserRequest, opts ...grpc.CallOption) (*ValidateUserReply, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoReply, error)
	GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoReply, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) ValidateUserPassword(ctx context.Context, in *ValidateUserRequest, opts ...grpc.CallOption) (*ValidateUserReply, error) {
	out := new(ValidateUserReply)
	err := grpc.Invoke(ctx, "/account.Account/validateUserPassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoReply, error) {
	out := new(GetUserInfoReply)
	err := grpc.Invoke(ctx, "/account.Account/getUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetTokenInfo(ctx context.Context, in *GetTokenInfoRequest, opts ...grpc.CallOption) (*GetTokenInfoReply, error) {
	out := new(GetTokenInfoReply)
	err := grpc.Invoke(ctx, "/account.Account/getTokenInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountServer interface {
	ValidateUserPassword(context.Context, *ValidateUserRequest) (*ValidateUserReply, error)
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoReply, error)
	GetTokenInfo(context.Context, *GetTokenInfoRequest) (*GetTokenInfoReply, error)
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_ValidateUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ValidateUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/ValidateUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ValidateUserPassword(ctx, req.(*ValidateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetTokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetTokenInfo(ctx, req.(*GetTokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "validateUserPassword",
			Handler:    _Account_ValidateUserPassword_Handler,
		},
		{
			MethodName: "getUserInfo",
			Handler:    _Account_GetUserInfo_Handler,
		},
		{
			MethodName: "getTokenInfo",
			Handler:    _Account_GetTokenInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_3a00d74cca72a020) }

var fileDescriptor_service_3a00d74cca72a020 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xd7, 0xad, 0x7f, 0x4f, 0xbb, 0x69, 0x73, 0xab, 0xa9, 0x0b, 0x20, 0x36, 0x8b, 0x49,
	0x93, 0x40, 0x19, 0x0a, 0x4f, 0xc0, 0x6e, 0x2a, 0x10, 0x43, 0x25, 0x6c, 0xdc, 0x4e, 0x5e, 0x72,
	0x56, 0x59, 0xa4, 0x71, 0xb0, 0x9d, 0x42, 0x79, 0x22, 0x9e, 0x8f, 0x27, 0x40, 0xfe, 0xd3, 0x90,
	0xb2, 0x32, 0xed, 0xf2, 0x9c, 0xef, 0xf8, 0x7c, 0x9f, 0x7f, 0x36, 0xec, 0x2a, 0x94, 0x0b, 0x9e,
	0x60, 0x58, 0x48, 0xa1, 0x05, 0xe9, 0xb0, 0x24, 0x11, 0x65, 0xae, 0x83, 0xe7, 0x33, 0x21, 0x66,
	0x19, 0x9e, 0xdb, 0xf6, 0x6d, 0x79, 0x77, 0xae, 0xf9, 0x1c, 0x95, 0x66, 0xf3, 0xc2, 0x4d, 0xd2,
	0x9f, 0xd0, 0xbc, 0x56, 0x28, 0x49, 0x00, 0xdd, 0x52, 0xa1, 0xcc, 0xd9, 0x1c, 0xc7, 0x8d, 0xe3,
	0xc6, 0x59, 0x2f, 0xae, 0x6a, 0x72, 0x02, 0x83, 0x94, 0xab, 0x22, 0x63, 0xcb, 0x1b, 0xab, 0x6f,
	0x5b, 0xbd, 0xef, 0x7b, 0x1f, 0xcd, 0xc8, 0x08, 0x5a, 0x38, 0x67, 0x3c, 0x1b, 0xef, 0x58, 0xcd,
	0x15, 0xe4, 0x19, 0x00, 0x5b, 0x30, 0xcd, 0xe4, 0x4d, 0x29, 0xb3, 0x71, 0xd3, 0x4a, 0x3d, 0xd7,
	0xb9, 0x96, 0x19, 0x3d, 0x82, 0xce, 0x67, 0x17, 0x9b, 0xec, 0xc1, 0x36, 0x4f, 0xbd, 0xf1, 0x36,
	0x4f, 0xe9, 0xaf, 0x06, 0xb4, 0xae, 0xc4, 0x57, 0xcc, 0xc9, 0x29, 0xb4, 0xb9, 0x52, 0x25, 0x4a,
	0xab, 0xf6, 0xa3, 0xdd, 0xd0, 0xdf, 0x2d, 0x34, 0xb9, 0x63, 0x2f, 0x92, 0x57, 0xd0, 0x65, 0x65,
	0xca, 0x31, 0x4f, 0x5c, 0xbe, 0x7e, 0xb4, 0x5f, 0x0d, 0x7a, 0x93, 0xb8, 0x9a, 0x20, 0x11, 0xb4,
	0xf1, 0x47, 0xc1, 0x25, 0xda, 0xbc, 0xfd, 0x28, 0x08, 0x1d, 0xa7, 0x70, 0xc5, 0x29, 0xbc, 0x5a,
	0x71, 0x8a, 0xfd, 0x24, 0x39, 0x84, 0xb6, 0x4a, 0x44, 0x81, 0x6a, 0xdc, 0x3c, 0xde, 0x39, 0xeb,
	0xc5, 0xbe, 0xa2, 0x97, 0x30, 0xfc, 0xc2, 0x32, 0x9e, 0x32, 0x8d, 0x36, 0x11, 0x7e, 0x2b, 0x51,
	0xe9, 0x07, 0x81, 0x06, 0xd0, 0x2d, 0x98, 0x52, 0xdf, 0x85, 0x4c, 0x3d, 0xcc, 0xaa, 0xa6, 0x1f,
	0xe0, 0x60, 0x7d, 0x5d, 0x91, 0x2d, 0x0d, 0xde, 0x85, 0x69, 0xda, 0x4d, 0xdd, 0xd8, 0x15, 0xe4,
	0x04, 0x9a, 0x66, 0xa5, 0xbf, 0xef, 0x3f, 0x60, 0xac, 0x44, 0x5f, 0x03, 0x99, 0xa0, 0x36, 0x8d,
	0x77, 0xf9, 0x9d, 0x78, 0x44, 0x36, 0x7a, 0x09, 0xfb, 0x6b, 0x27, 0x8c, 0xfd, 0xa1, 0xc1, 0xc5,
	0x95, 0x56, 0xde, 0xdf, 0x57, 0x8f, 0x09, 0xf0, 0x12, 0x86, 0x13, 0xd4, 0xf6, 0x29, 0xeb, 0x09,
	0x46, 0xd0, 0xd2, 0xa6, 0xe7, 0xed, 0x5d, 0x41, 0x3f, 0xc1, 0xc1, 0xfa, 0xf0, 0x43, 0xe6, 0x2f,
	0x56, 0x2b, 0x9c, 0xfb, 0x5e, 0xe5, 0x6e, 0xcf, 0xfb, 0x95, 0xd1, 0xef, 0x06, 0x74, 0xde, 0x3a,
	0x81, 0xc4, 0x30, 0x5a, 0xd4, 0xd0, 0x4e, 0x3d, 0x72, 0xf2, 0xb4, 0x3a, 0xba, 0xe1, 0x21, 0x83,
	0xe0, 0x3f, 0x6a, 0x91, 0x2d, 0xe9, 0x16, 0x99, 0x40, 0x7f, 0xf6, 0x17, 0x17, 0x79, 0x52, 0x0d,
	0xdf, 0xc7, 0x1e, 0x1c, 0x6d, 0x16, 0xdd, 0xa2, 0xf7, 0x30, 0x98, 0xd5, 0xee, 0x5e, 0x0b, 0xb5,
	0x81, 0x5f, 0x2d, 0xd4, 0x3d, 0x60, 0x74, 0xeb, 0xe2, 0x14, 0x86, 0x49, 0x26, 0xca, 0x34, 0x5c,
	0x2a, 0xae, 0xd3, 0xd5, 0xe8, 0xc5, 0xc0, 0x83, 0x98, 0x9a, 0x4f, 0x3e, 0x6d, 0xdc, 0xb6, 0xed,
	0x6f, 0x7f, 0xf3, 0x27, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xa8, 0xf8, 0x31, 0x3d, 0x04, 0x00, 0x00,
}
